### ISSUE TITLE
Change the font from Overpass to Inter

### ISSUE THREAD

**Issue by AVS1508** [umass-cicsoft/umass-cicsoft.github.io#14]
As the title suggests, we need to change the font of the website from `Overpass` to `Inter`. Since both are Google Fonts, the changes will be simple:

1. Change the import statement in the `main.css` to be: 
~~~ 
@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
~~~
2. Change the body tag CSS rule to be:
~~~
body {
    font-family: "Inter", sans-serif;
}
~~~
EDIT: Had written the incorrect import, corrected it.

**Comment by pritshah9** [comment]
Do you want to import this one? 

`@import url('https://rsms.me/inter/inter.css');`

**Comment by AVS1508** [comment]
I think that's the same typeface, so no issues! I did see I had written the incorrect import URL, but I have rectified that error.
