### ISSUE TITLE
[FEATURE REQUEST]  Add 'Syllabus' as link in the navigation bar

### ISSUE THREAD

**Issue by AVS1508** [umass-cicsoft/umass-cicsoft.github.io#25]
### **Is your feature request related to a problem? Please describe.**
As discussed in the meeting on 30th December 2021, we need to add 'Syllabus' as a section on our website, thus, we need to have a corresponding link in the navigation bar.

### **Describe the solution you would like**
Add 'Syllabus' as a link in the navigation bar, using the following syntax:

```HTML
<li class="nav-item">
    <a class="nav-link" href="#">TEAM</a>
</li>
```
**UPDATE**: Remove the 'Contact' tab from the navigation bar. The 'Syllabus' tab should go well in place of the 'Team' tab and the 'Team' tab should replace the position of the 'Contact' tab. The final order will be: 
```markdown
ABOUT | APP SHOWCASE | SYLLABUS | APPLY | FAQS | TEAM
```

### **Describe alternatives you have considered**
No reason to consider alternatives.

### **Additional Context**
Sufficiently explained the context in the original requirement.

**Comment by pritshah9** [comment]
We also discussed removing the Contact tab from the bar. I was thinking the syllabus might go well in place of the team tab and the team tab should replace the contact tab.

**Comment by AVS1508** [comment]
@pritshah9 I agree! That sounds like a good plan, I'll edit the issue description to reflect the same!
