### ISSUE TITLE
[BUG] Lab Idea Form Email not being saved

### ISSUE THREAD

**Issue by kiratarora** [umass-cicsoft/umass-cicsoft.github.io#77]
### **Bug Description**
The emails entered by the user is not getting stored in the database. 

###  **To Reproduce**
Steps to reproduce the behaviour:
1. Fill out the lab idea form
2. Check the data in firebase

### **Expected Behavior**
The email of the sender should be stored in the database.

**Comment by AVS1508** [comment]
Fixed through:
- https://github.com/umass-cicsoft/CICapi/pull/7
- #78
