### ISSUE TITLE
[FEATURE REQUEST] Add information about CICSoft tech hour and remove the last line about appathon from the about section. 

### ISSUE THREAD

**Issue by kiratarora** [umass-cicsoft/umass-cicsoft.github.io#79]
### **Is your feature request related to a problem? Please describe.**
We do not have any plans to have an appathon anytime soon, so I feel like we should remove that part. 

### **Describe the solution you would like**
Instead, we should add our ideas about the tech hours there.

**Comment by AVS1508** [comment]
That sounds good! We should ask the Core Team to come up with a blurb on the CICSoft TechHour, in particular, the Logistics and Social Media teams.
